### PR TITLE
Ignore unnecessary files in the release

### PR DESCRIPTION
**Pull request by erikn69**
Please see https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files

### CODE REVIEW

**Comment by Maxouhell** [comment]
But... I can't ignore the d.ts !
It's a needed file for peoples who are using Typescript 👀

**Comment by erikn69** [comment]
What?? 

This pr is not ignoring the `d.ts` file, it is adding it to the default files

> Please see https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files

Did you read the link??

```batch
# npm publish --dry-run
npm notice
npm notice 📦  x2js@3.4.4
npm notice === Tarball Contents ===
npm notice 4.1kB  CHANGELOG.md
npm notice 11.6kB LICENSE
npm notice 4.0kB  README.md
npm notice 2.1kB  package.json
npm notice 7.8kB  x2js.d.ts
npm notice 25.2kB x2js.js
npm notice === Tarball Details ===
npm notice name:          x2js
npm notice version:       3.4.4
npm notice filename:      x2js-3.4.4.tgz
npm notice package size:  16.1 kB
npm notice unpacked size: 54.7 kB
npm notice shasum:        d586e3c5177bc808705002dd3d06465ce72878e6
npm notice integrity:     sha512-Cl4jIEGSi9ZHw[...]9ujmvggIADD6g==
npm notice total files:   6
npm notice
+ x2js@3.4.4
```
PD: I'm using typescript

**Comment by Maxouhell** [comment]
Ok sorry, I'm not english native sometimes I don't understand it very well :)

**Comment by erikn69** [comment]
> I'm not english native sometimes I don't understand it very well

Me too, it also happens to me often

**Pull request merged**
